service: perform-server
runtime: nodejs10
instance_class: F1
automatic_scaling:
  max_instances: 1
  # Could maybe increase to 1?
  min_instances: 0
  max_idle_instances: 1
    # Could maybe increase to 1?
  min_idle_instances: 0
