/**
 * Project Perform API V1
 * V1.x.x cover the API for one team
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cname@yahoo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Error report
 */
export interface ModelError {
  code: number;
  message: string;
}
